### ISSUE TITLE
Plugin version 1.6.0 conflicts with Gradle feature DependencyResolutionManagement option FAIL_ON_PROJECT_REPOS

### ISSUE THREAD

**Issue by ELynx** [andygoossens/gradle-modernizer-plugin#2]
Hello,

in our multi-project Gradle build we use centralized repository declaration:

https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration

We also enforce the centralized policy, as in `Example 21. Enforcing settings repositories`:

```
ependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
}
```

Applying plugin, with option on, causes exception on configuring project

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'foobar'.
...
Caused by: org.gradle.api.InvalidUserCodeException: Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'com.github.andygoossens.gradle-modernizer-plugin'
```

Commenting out FAIL_ON_PROJECT_REPOS line allows project to be configured.

We use Gradle version 7.2.0. If necessary, I can make a sample project, I am 90% certain this is reproducible independent of project.

I think incompatibility is caused by https://github.com/andygoossens/gradle-modernizer-plugin/blob/ebc83874fdde61099a0a6ed31af62962aa425c00/src/main/groovy/com/github/andygoossens/gradle/plugins/ModernizerPlugin.groovy#L38

**Comment by andygoossens** [comment]
Thanks for your report.

I didn't know about this Gradle setting and as such I obviously did not test this scenario. But it makes sense and so I want to support it from now on.

You are right, that line of code causes the issue. I wanted to be as foolproof as possible with all kinds of repository setups, but in the end it is a kind of hack. There won't be many Gradle plugins that do something similar.

I will remove those lines, which will have as consequence that `mavenCentral()` repository needs to be configured somewhere. This can be in `settings.gradle(.kts)` or a project's `build.gradle(.kts)` (unless you use FAIL_ON_PROJECT_REPOS), but it may no longer be a buildscript repository.

**Comment by andygoossens** [comment]
Fixed in version [1.6.1](https://github.com/andygoossens/gradle-modernizer-plugin/releases/tag/1.6.1)

**Comment by ELynx** [comment]
Thank you!

Tested and works on gradle multi-project build.

Our project needed some tweaking to how plugin is applied, because root project has no source sets.

Here are quots from root `build.gradle` that worked for us:

```groovy
plugins {
  id 'com.github.andygoossens.modernizer' version '1.6.1' apply false
  // more plugins omitted
}

// build stuff

def javaProjects() {
  subprojects.findAll { subproject ->
    subproject.plugins.hasPlugin('java')
  }
}

gradle.beforeProject {
  configure(javaProjects()) {
    apply plugin: 'com.github.andygoossens.modernizer'
  }
}

// more build stuff
```

**Comment by andygoossens** [comment]
I have updated the README.md file to clarify what people should use when the root project has no source set. Gradle is sometimes too flexible for its own good. :-)

Ideally you apply the modernizer plugin everywhere you apply the java plugin as well.

With Gradle's old way:
```groovy
apply plugin: 'java'
apply plugin: 'com.github.andygoossens.modernizer'
```

With Gradle's new way:
```groovy
plugins {
  id 'java'
  id 'com.github.andygoossens.modernizer'
}
```

Mentioning this in each one of your (sub)projects would be tedious. So you may want to use convention plugins instead: https://docs.gradle.org/current/userguide/structuring_software_products.html
I am converting my own projects to this structure. But updating existing large code bases to this structure can be a daunting task.

**Comment by ELynx** [comment]
In our project not even all subprojects are java. We have dedicaded subproject for making documentation pages, and IIRC there are some others that do not have 'java' plugin applied for whatever reasons. That `def javaProjects()` was there before I added this plugin =)
